app:
  jwt:
    secret: test
    #expiration time in milliseconds
    expiration: 36000000

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/java_sql_notifier?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: pwd